cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'coreutils'
brew 'curl'
brew 'git'
brew 'htop-osx'
brew 'lua51'
brew 'luajit'
brew 'node', args: ['with-full-icu']
brew 'openresty'
brew 'openssl'
brew 'php70'
brew 'php70-intl'
brew 'php70-opcache'
brew 'php70-xdebug'
brew 'readline'
brew 'redis'
brew 'rlwrap'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'
brew 'zsh'

cask '1password'
cask 'adium'
cask 'firefox'
cask 'google-chrome'
cask 'opera'
cask 'handbrake'
cask 'transmission'
cask 'vlc'
cask 'launchrocket'
cask 'commander-one'
cask 'macdown'
cask 'sourcetree'
cask 'franz'
cask 'ccleaner'
cask 'coolterm'
cask 'fritzing'
cask 'wireshark'
cask 'xtrafinder'
cask 'rowanj-gitx'
cask 'libreoffice'
cask 'commander-one'
cask 'macdown'
cask 'xquartz'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'betterzipql'
cask 'qlimagesize'
cask 'suspicious-package'
cask 'qlvideo'
