#!/usr/bin/env sh
#
# Run all dotfiles installers.

set -e

cd "$DOTFILES_ROOT"

# Run Homebrew through the Brewfile
echo "› brew bundle"
brew bundle

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
