# Aliases
alias mkdir='nocorrect mkdir -p'
alias cp='nocorrect cp -R'
alias mv='nocorrect mv'
alias which='nocorrect which'
alias source='nocorrect source'
alias man='nocorrect man'
alias git='nocorrect git'
alias h='history'
alias history='fc -l 1'
alias j='jobs -l'
alias ..='cd ..'
alias path='echo -e ${PATH//:/\\n}'
alias du='du -h'
alias df='df -h'
alias ls='ls -F'
alias ll='ls -lFh'
alias la='ls -alFh'
alias ldot='ls -ld .*'
alias less='less -M'
alias xs='cd'
alias vf='cd'
alias moer='more'
alias moew='more'
alias kk='ll'
alias sshx='export DISPLAY=:0.0 && open /Applications/Utilities/X11.app && ssh -X'
alias lssh='ssh -o StrictHostKeyChecking=no -o GlobalKnownHostsFile=/dev/null -o UserKnownHostsFile=/dev/null -o ConnectionAttempts=35 -o ConnectTimeout=1 '
#alias dxt='xtitle `basename $PWD`'
alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain system -domain user'
alias wget='wget -c'
alias grep='nocorrect grep --color=auto'
alias fd='find . -type d -name'
alias ff='find . -type f -name'
alias t='tail -F'
alias zshrc='vim ~/.zshrc'
alias luajit='rlwrap luajit'
alias lua='rlwrap lua'
alias lua5.1='rlwrap lua5.1'
alias lua5.2='rlwrap lua5.2'
alias lua5.3='rlwrap lua5.3'

alias -g N='2>/dev/null'
alias -g L='| less'
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"
